networks:
  apollo:
    external: true

services:
  import_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: import_api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
    networks:
      - apollo
