services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app_container
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development  
    volumes:
      - .:/app  
    command: flask run --host=0.0.0.0